### ISSUE TITLE
info/desc API 에러

### ISSUE THREAD

**Issue by yunseo-h68** [Ho-Joon-Kim/dsm-infographic#14]
백엔드 서버를 구동한 후,
http://localhost:8080/api/info/desc?imgid=27로 접속했을 때, 아래와 같은 에러 발생

```
Cannot read property 'infoN' of undefined
```

**Comment by Ho-Joon-Kim** [comment]
json파일에러로 판단됨 시간필요

**Comment by Ho-Joon-Kim** [comment]
해결. 메일확인바람

**Comment by yunseo-h68** [comment]
여전히 오류 있음

**Comment by yunseo-h68** [comment]
Cannot read property 'infoN' of undefined

**Comment by yunseo-h68** [comment]
에러 원인 발견함. 

survey.json에 data가 1부터 27까지 있어야 하지만 26까지 있어 데이터가 누락됨.

16번과 17번 사이에 "예뻐질수록 건조해진다"라는 타이틀을 가진 Infographic data가 누락됨.

추가바람
