### ISSUE TITLE
detailImage 컴포넌트의 개발 필요

### ISSUE THREAD

**Issue by yunseo-h68** [Ho-Joon-Kim/dsm-infographic#15]
세로 이미지 뿐만 아니라 가로이미지 친화적인 것도 추가 필요

인포그래픽 이미지의 경우, A3사이즈를 축소해둔것이기 때문에 자세하게 안보인다.
그러므로 돋보기 기능 혹은 Survey를 지운 이미지만 있는 기능이 필요하다.

**Comment by Ho-Joon-Kim** [comment]
이미지를 클라이언트단에서 90도 돌려서 이미지만 있는 기능을 구현하면 새로운 api 추가할 필요 없이 구현할 수 있을것

**Comment by yunseo-h68** [comment]
survey를 하는 컴포넌트(Infographic-Detial)에서 현재는 세로형에 친화적인 UI만 있지만 컴포넌트에서 매개변수로 받아 그 값에 따라 세로형, 가로형으로 렌더링할 수 있도록 구현예정.이미지의 경우, 90도 돌려서 사용할 예정.

**Comment by yunseo-h68** [comment]
survey를 하는 컴포넌트인 InfographicDetail에서 이미지를 클릭하면 이미지만 크게 보이도록 계획을 수정함

infographicDetail의 하위 컴포넌트 detailImage컴포넌트를 개발하기로 함
