### ISSUE TITLE
사용자의 Survey 여부를 반환하는 API 추가 요청

### ISSUE THREAD

**Issue by yunseo-h68** [Ho-Joon-Kim/dsm-infographic#16]
infographic 작품의 아이디(infoNum)과 User의 Id를 Post로 보내면 Survey를 여부를 반환하는 API 필요

사용자가 Survey를 했는지 확인하여 style을 다르게 하기 위해서 필요. 사용자에게 자신이 Survey한 Infographic이 무엇인지 알리기 위한 목적.

**Comment by Ho-Joon-Kim** [comment]
완성
