### ISSUE TITLE
Infographic Data 오류 - 잘못된 매치 and 데이터 누락

### ISSUE THREAD

**Issue by yunseo-h68** [Ho-Joon-Kim/dsm-infographic#17]
인포그래픽 작품의 이미지와 설명이 잘못 매치된 부분이 있으며, 
survey.json에서 16번과 17번 사이에 "예뻐질수록 건조해진다" data가 누락됨

이로 인해, desc API에서 오류가 발생함.

**Comment by yunseo-h68** [comment]
info/desc의 동작 자체는 정상적으로 잘 동작하지만, data의 오류, 누락으로 인해 예상치 못한 에러가 발생한다.

**Comment by Ho-Joon-Kim** [comment]
txt 파일 이름 오류로 판단, 수정완료 메일 확인 바람
