### ISSUE TITLE
POST /api/survey 404 Error

### ISSUE THREAD

**Issue by yunseo-h68** [Ho-Joon-Kim/dsm-infographic#21]
`api/survey`로 평가데이터를 POST로 보내자, 404 에러가 발생함

**Comment by Ho-Joon-Kim** [comment]
일단 퍼블릭 폴더의 문제일 수도 있으니 다시 보내놓음 확인바람

**Comment by Ho-Joon-Kim** [comment]
또한 이 문제는 상대 주소의 문제일 거라고 판단됨 포스트맨으로 보내봤으나 잘 됬었음

**Comment by yunseo-h68** [comment]
public 폴더 업데이트 이후에도 같은 결과 발생

**Comment by yunseo-h68** [comment]
혹시 API 문서 업데이트 했나요?
survey api 스펙 확인하시고, 완료된 거라면 `o` 표시를 남겨주세요.
그러면 거기에 맞춰서 다시 front쪽 send 코드 확인해보겠습니다.

**Comment by Ho-Joon-Kim** [comment]
오래된 코드가 올라가있을 가능성 생각후 다시 푸시함 확인바람
