### ISSUE TITLE
로그인 API 에러

### ISSUE THREAD

**Issue by yunseo-h68** [Ho-Joon-Kim/dsm-infographic#4]
user id 값으로 사전에 설정한 "1111"로 보내지 않으면 서버측에서 500 서버오류를 반환함.

user id 값으로 "1111", user password로 "wefwefwe"를 보내면 정상적으로 loginchk false를 반환하지만  
user id 값으로 "1234", user password로 "wervwfwe"를 보내면 500 서버 오류가 발생한다.

**Comment by yunseo-h68** [comment]
routes/login.js에서 아래의 코드가 발생시키는 에러인 것 같으니 아래의 코드를 지워주세요.

```javascript
console.log(user[user_id]["pswd"])
```

**Comment by Ho-Joon-Kim** [comment]
해결했습니다
