### ISSUE TITLE
Survey API 개발 필요

### ISSUE THREAD

**Issue by yunseo-h68** [Ho-Joon-Kim/dsm-infographic#9]
Survey API 개발이 필요함.
frontend에서 survey 결과를 보내면 서버에선 404 에러를 발생시키고 있음.
Survey API 개발 후, 아래와 같은 라우팅 설정 필요.(servey에서 survey로 오타 수정 바람)

```js
//var serveyRouter = require('./routes/servey');
````

**Comment by yunseo-h68** [comment]
Survey API 경우, 결과를 User별로 저장해야 하지 않나요?
동작 방식이 지금은 Infographic에 대한 총점을 구하는 것 같은데.

**Comment by Ho-Joon-Kim** [comment]
의견 수렴후 개발 완료
